# Generated by Django 6.0.3 on 2026-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpattempt',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
