# Generated by Django 6.0.3 on 2026-04-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpattempt_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpattempt',
            name='action',
            field=models.CharField(choices=[('send', 'Send'), ('verify', 'Verify'), ('reset_send', 'Reset Send'), ('reset_verify', 'Reset Verify')], max_length=20),
        ),
    ]
