# Generated by Django 6.0.3 on 2026-04-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='interests.interest'),
        ),
    ]
